# Generated by Django 5.0.3 on 2024-06-01 23:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dish', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='orderdish',
            name='dish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dish.dish', verbose_name='Блюдо'),
        ),
        migrations.AddField(
            model_name='orderdish',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dish.order', verbose_name='Заказ'),
        ),
        migrations.AddField(
            model_name='order',
            name='dishes',
            field=models.ManyToManyField(through='dish.OrderDish', to='dish.dish', verbose_name='Блюда'),
        ),
        migrations.AddField(
            model_name='dish',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dish.type', verbose_name='Тип'),
        ),
    ]
