# Generated by Django 5.0.3 on 2024-06-01 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dish", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="orderdish",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="order",
            name="total_cost",
            field=models.PositiveSmallIntegerField(
                default=0, verbose_name="Общая стоимость"
            ),
        ),
    ]
